# Generated by Django 3.2.3 on 2021-05-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
