# Generated by Django 3.2.3 on 2021-05-20 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0003_rename_review_review_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reviews',
            new_name='review',
        ),
    ]
